# Generated by Django 5.1.3 on 2024-11-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"verbose_name": "привычка", "verbose_name_plural": "привычки"},
        ),
        migrations.RemoveField(
            model_name="habit",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="time_to_execute",
        ),
        migrations.AddField(
            model_name="habit",
            name="duration",
            field=models.SmallIntegerField(
                default=1,
                help_text="Время, которое предположительно потратит пользователь на выполнение привычки в минутах",
                verbose_name="Время на выполнение",
            ),
            preserve_default=False,
        ),
    ]
