# Generated by Django 5.1.3 on 2024-11-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_options_remove_habit_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Чем пользователь должен себя вознаградить после выполнения",
                max_length=200,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
    ]
